### PR TITLE
Added a changelog feature

### PR DESCRIPTION
**Pull request by robojumper**
With help from BlueRaja.
Visual Studio reordered the lines in MainForm.Designer.cs, hence the deletions.

### CODE REVIEW

**Comment by BlueRaja** [comment]
Other than the small suggestions above, looks good, nice job!

_(Since you said you're new to Github:)_  You can push any additional changes to your branch and they'll get reflected automatically, you don't need to open a new PR.

**Comment by robojumper** [comment]
How does this ContinueWith() thing work? Setting the textbox text via changelog.Result causes a System.InvalidOperationException because the access occurred from a different thread?

**Comment by BlueRaja** [comment]
Oh, right, derp.  You'll either have to call `Invoke` on the control, or use `await` instead of `ContinueWith`.  I'd say do the latter, it's simpler.

More on `Invoke`: http://stackoverflow.com/questions/14703698/invokedelegate

**Comment by aEnigmatic** [comment]
Hey, thanks for the PR!

1 very minor thing: 
Can you change the namespace in ModChangelogCache to XCOM2Launcher.Mod (- Classes).

**Comment by BlueRaja** [comment]
LGTM! :+1:

**Pull request merged**
